language: go
go:
  - "1.13.x"

services:
  - postgresql

env:
  - GO111MODULE=on

install: true


jobs:
  include:
    - stage: build docker image
      script: docker build -t bashhub-server .
    - stage:  run server
      script: docker run --rm -d bashhub-server
    - stage: ping docker server
      script: curl http://localhost:8080/ping
    - stage: test
      script: go test ./... && go test github.com/nicksherron/bashhub-server/internal -postgres-uri "postgres://postgres:@localhost:5432?sslmode=disable"
