language: go
go:
  - "1.14.x"

services:
  - postgresql
  - docker

env:
  - GO111MODULE=on

before_install:
  - docker build -t nicksherron/bashhub-server .
  - docker run -d -p 127.0.0.1:8080:8080  nicksherron/bashhub-server
  - curl 127.0.0.1:8080/ping

script: go test ./... && go test github.com/nicksherron/bashhub-server/internal -postgres-uri "postgres://postgres:@localhost:5432?sslmode=disable"
